# Generated by Django 3.1 on 2020-10-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vcard',
            name='id',
        ),
        migrations.AlterField(
            model_name='vcard',
            name='prenom',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
