# Generated by Django 3.1 on 2020-10-30 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Certificats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('school', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='LangCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='PrinCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Principles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('snipet', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('certificats', models.ManyToManyField(blank=True, null=True, through='portfolio.CertCat', to='portfolio.Certificats')),
                ('languages', models.ManyToManyField(blank=True, null=True, through='portfolio.LangCat', to='portfolio.Languages')),
                ('principles', models.ManyToManyField(blank=True, null=True, through='portfolio.PrinCat', to='portfolio.Principles')),
            ],
        ),
        migrations.CreateModel(
            name='Softwars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='SofCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.softwars')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.services')),
            ],
        ),
        migrations.AddField(
            model_name='services',
            name='softwars',
            field=models.ManyToManyField(blank=True, null=True, through='portfolio.SofCat', to='portfolio.Softwars'),
        ),
        migrations.AddField(
            model_name='princat',
            name='principles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.principles'),
        ),
        migrations.AddField(
            model_name='princat',
            name='services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.services'),
        ),
        migrations.AddField(
            model_name='langcat',
            name='certificats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.languages'),
        ),
        migrations.AddField(
            model_name='langcat',
            name='services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.services'),
        ),
        migrations.AddField(
            model_name='certcat',
            name='certificats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.certificats'),
        ),
        migrations.AddField(
            model_name='certcat',
            name='services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.services'),
        ),
    ]
