# Generated by Django 3.1 on 2020-11-02 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20201102_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='langcat',
            old_name='certificats',
            new_name='languages',
        ),
        migrations.RenameField(
            model_name='sofcat',
            old_name='certificats',
            new_name='softwars',
        ),
        migrations.RemoveField(
            model_name='langcat',
            name='title',
        ),
    ]
